# Site settings
title: ERIC CULHANE
email: eric.culhane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  EDITOR  

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Collections:
collections:
  # editing:
  #   output: true
  # new-media:
  #   output: true
  # videography:
  #   output: true
  portfolio:
    output: true


# Build settings
markdown: kramdown
permalink: pretty
