# Site settings
title: Eric Culhane
email: eric.culhane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Collections:
collections:
  editing:
    output: true
  new-media:
    output: true
  videography:
    output: true


# Build settings
markdown: kramdown
permalink: pretty
